### ISSUE TITLE
[🙏] Make version and severity fields optional

### ISSUE THREAD

**Issue by HadleRS** [snyk-tech-services/snyk-licenses-texts#94]
**Describe the user need**
It would be nice if  Snyk could make the version and severity fields optional.

**Describe expected behaviour**

For version:
Instead of showing "requests@2.26.0" we would like to only see "requests"
For severity:
Instead of seeing "Severities: "none", "none"," we would like for it to be removed.

**Comment by lili2311** [comment]
hi @HadleRS, the tool accepts a customized template so users can remove any data they do not need. 

Severity is already optional and can be toggled on off with `--excludeSnykFields`, please see the `help` command for full list of available options.

For any further changes please have a look at:
`snyk-licenses-report generate --orgPublicId=<ORG_PUBLIC_ID> --template="PATH/TO/TEMPLATE/template.hsb"`
The data in the template is available is in the format:
```{
  licenses: LicenseReportData;
  orgPublicId: string;
  orgData: OrgData;
}
```

The types can be seen in the template or the TypeScript types. For you scenario you would modify the existing template and drop the fields you do not wish to see. I would copy paste the template into a new file and drop the `version` property
https://github.com/snyk-tech-services/snyk-licenses-texts/blob/master/src/lib/generate-report/templates/licenses-view.hbs#L185
