### ISSUE TITLE
[🙏] Add comments from unknown licenses as optional field

### ISSUE THREAD

**Issue by HadleRS** [snyk-tech-services/snyk-licenses-texts#95]
**Describe the user need**
For a few dependencies Snyk is not able to find the license and will label it unknown. We have solved these with a comment on the dependency in the GUI.
Consequently we would want Snyk to make it possible to fetch comments about unknown licenses, maybe as an optional field, instead of having to do this manually after creating the document.

**Comment by lili2311** [comment]
Hi @HadleRS similar to another issue, the current APIs used do not have this data. We will log this as a feature request for that API
