### ISSUE TITLE
[🙏] Make it possible to run from specific commit/release

### ISSUE THREAD

**Issue by HadleRS** [snyk-tech-services/snyk-licenses-texts#96]
**Describe the user need**
I want Snyk to be able to specify a commit/release to run the snyk-licenses-texts on. Currently using the GitHub integration it will only use the latest base branch. But we would need it to also support setting custom release branches/commits which are not always the same as base branch.

**Describe expected behaviour**
Being able to specify a certain commit or branch/release-tag, for examples like this:
./snyk-licenses-texts-linux generate -b 1.4.6
or with commit:
./snyk-licenses-texts-linux generate -b 43547648

**Comment by lili2311** [comment]
Hi @HadleRS, this tool uses available Snyk APIs. We do not have ability to choose commits via the APIs used by this which is Dependencies & Licenses APIs from https://snyk.docs.apiary.io. We will record this internally as a feature request for those APIs.
